### ISSUE TITLE
Not available to download the indices 

### ISSUE THREAD

**Issue by hanszzz** [tzuhsial/edgar-10k-mda#3] opened 2020-01-24 20:03 UTC
Hi, I am very new to Python coding, so maybe I am missing something. If anyone could resolve my issue, I would appreciate a lot! 

When I run step 1 code, I get an error message saying: 
(request index - https://www.sec.gov/Archives\edgar\full-index\2016\QTR1\form.idx
writing index to ./index\year2016_qtr1.index
download index failed - https://www.sec.gov/Archives\edgar\full-index\2016\QTR1\form.idx)

Below are my steps to use the provided codes. 
1) download Miniconda 
2) install most recent version of: python, requests, BeautifulSoup, docopt, tqdm, csv, itertools, os, re, unicodedata, namedtuple, glob. 
3) Change cd to the correct folder in Miniconda
4) Copy and Paste "python edgar.py download index --year-start=2016 --year-end=2016 --index-dir=./index  --index-10k-path=index.10k.csv" 

ps. I really thanks to the writer of the code who shared his knowledge!

**Comment by tzuhsial** [comment] 2020-01-25 02:57
Hey @hanszzz, 

I wasn't able to reproduce your error.  Lazy me was able to successfully run the following commands.

```bash
python edgar.py download index
python edgar.py download 10k
python edgar.py extract mda
```

I've modified the code a bit to print the error messages.  Could you run `git pull` to get the lataset commit and rerun these the command (without any arguments) I listed above?

**Comment by hanszzz** [comment] 2020-01-26 20:42
Dear @tzuhsial  Thanks for the reply. I just have downloaded new .zip file and ran the code (wasn't sure how to update the current code by git pull. Still downloading indices was not successful. Below is the input and output msgs I got on Miniconda3. Thannks!  


(base) C:\Users\Han>cd Desktop\Python\Parsing\edgar-10k-mda-master

(base) C:\Users\Han\Desktop\Python\Parsing\edgar-10k-mda-master>python edgar.py download index
{'--10k-dir': './form10k',
 '--index-10k-path': './index.10k.csv',
 '--index-dir': './index',
 '--mda-dir': './mda',
 '--year-end': '2016',
 '--year-start': '2016',
 '10k': False,
 'download': True,
 'extract': False,
 'index': True,
 'mda': False}
request index - https://www.sec.gov/Archives\edgar\full-index\2016\QTR1\form.idx
writing index to ./index\year2016_qtr1.index
'charmap' codec can't encode characters in position 22676-22677: character maps to <undefined>
request index - https://www.sec.gov/Archives\edgar\full-index\2016\QTR2\form.idx
writing index to ./index\year2016_qtr2.index
'charmap' codec can't encode characters in position 22676-22677: character maps to <undefined>
request index - https://www.sec.gov/Archives\edgar\full-index\2016\QTR3\form.idx
writing index to ./index\year2016_qtr3.index
'charmap' codec can't encode characters in position 22676-22677: character maps to <undefined>
request index - https://www.sec.gov/Archives\edgar\full-index\2016\QTR4\form.idx
writing index to ./index\year2016_qtr4.index
'charmap' codec can't encode characters in position 22676-22677: character maps to <undefined>
Extracting 10k records from index ./index\year2016_qtr1.index
Extracting 10k records from index ./index\year2016_qtr2.index
Extracting 10k records from index ./index\year2016_qtr3.index
Extracting 10k records from index ./index\year2016_qtr4.index

(base) C:\Users\Han\Desktop\Python\Parsing\edgar-10k-mda-master>python edgar.py download 10k
{'--10k-dir': './form10k',
 '--index-10k-path': './index.10k.csv',
 '--index-dir': './index',
 '--mda-dir': './mda',
 '--year-end': '2016',
 '--year-start': '2016',
 '10k': True,
 'download': True,
 'extract': False,
 'index': False,
 'mda': False}

(base) C:\Users\Han\Desktop\Python\Parsing\edgar-10k-mda-master>python edgar.py extract mda
{'--10k-dir': './form10k',
 '--index-10k-path': './index.10k.csv',
 '--index-dir': './index',
 '--mda-dir': './mda',
 '--year-end': '2016',
 '--year-start': '2016',
 '10k': False,
 'download': False,
 'extract': True,
 'index': False,
 'mda': True}
0it [00:00, ?it/s]

**Comment by tzuhsial** [comment] 2020-01-27 00:16
@hanszzz Are you sure you're using python3?  You'll need to wait for the previous step to finish (which might take some time) before running the next step.

**Comment by hanszzz** [comment] 2020-01-27 19:52
Yes :( I did some research and found out that Windows need `,encoding="utf-8" ' inside `with open'. 
So, I added this to the code as below, and I did not get an error message. 
            with open(form_idx_path, 'w', encoding="utf-8") as fout:
                fout.write(res.text))

However, I wasn't still able to download the index files. Now, my downloaded index file is 40kb with weird msgs like:
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width initial-scale=1.0 maximum-scale=3.0" />
    <meta name="origin" content="WCM" />
    <script type="text/javascript">
	  WebFontConfig = {
	    google: { families: [ 'Raleway:300,400,500,600:latin' ] }
	  };
	  (function() {
	    var wf = document.createElement('script');
....

Hm...

**Comment by tzuhsial** [comment] 2020-01-28 00:59
@hanszzz I'm using Mac so I couldn't have found that error :(

The error I see looks like you've been blocked by the server (for sending too many requests).   I would suggest waiting for a day before trying again.

**Comment by tzuhsial** [comment] 2020-02-06 00:33
Closing issue as there seems to be no followup problems.

**Closed as completed by tzuhsial** 2020-02-06 00:33 UTC
